name: 'IntelliJ Plugin Verifier'
description: 'GitHub Action that verifies plugin compatibility with any version of IntelliJ IDEA.'
author: 'Pieter De Clercq <@thepieterdc>'
inputs:
  plugin:
    description: 'Path to the plugin distribution zip file'
    required: true
  verifier_version:
    description: 'The version of the Jetbains IntelliJ Verifier that you want to use'
    required: true
    default: '1.301'
  versions:
    description: 'The versions of IntelliJ that should be validated against'
    required: true
branding:
  color: 'green'
  icon: 'check-circle'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.plugin }}
    - ${{ inputs.verifier_version }}
    - ${{ inputs.versions }}
